[project]
name = "deepseek-planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.37.18",
    "mcp[cli]>=1.5.0",
    "python-dotenv>=1.0.1",
]
